version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/bob-25
    overwrite: yes
permissions:
  - object: /var/www/html/
    owner: root
    group: root
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.bash
  AfterInstall:
    - location: scripts/afterInstall.bash
